# Generated by cpp11: do not edit by hand

C_max_client_version <- function() {
  .Call(`_rib_C_max_client_version`)
}

C_decode_bin <- function(server_version, bin) {
  .Call(`_rib_C_decode_bin`, server_version, bin)
}

C_enc_reqMktData <- function(twsServerVersion, reqId, contract, genericTicks, snapshot, regulatorySnaphsot, mktDataOptions) {
  .Call(`_rib_C_enc_reqMktData`, twsServerVersion, reqId, contract, genericTicks, snapshot, regulatorySnaphsot, mktDataOptions)
}

C_enc_cancelMktData <- function(twsServerVersion, reqId) {
  .Call(`_rib_C_enc_cancelMktData`, twsServerVersion, reqId)
}
